"""add_merchant_onboarding_fields

Revision ID: da61b603b0a1
Revises: 04e3fbbaba28
Create Date: 2026-08-28 20:47:37.034390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da61b603b0a1'
down_revision: Union[str, None] = '04e3fbbaba28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('country', sa.String(length=50), nullable=False, server_default='India'))
    op.add_column('merchants', sa.Column('business_category', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'description')
    op.drop_column('merchants', 'business_category')
    op.drop_column('merchants', 'country')
    # ### end Alembic commands ###
