from decimal import Decimal
from pydantic import BaseModel, Field
from app.core.enums import EventProvenance


class MultiDimensionalAttribution(BaseModel):
    """Accurate multi-dimensional attribution schema preventing double counting."""
    order_id: str
    order_number: str
    total_paid_revenue: Decimal = Field(..., description="Actual merchant revenue collected from this order.")
    
    is_ai_assisted: bool = Field(False, description="Whether conversational AI or recommendations influenced the order.")
    baseline_revenue: Decimal = Field(Decimal("0.00"), description="Organic catalog baseline value.")
    ai_incremental_revenue: Decimal = Field(Decimal("0.00"), description="Incremental revenue generated by AI add-ons/bundles.")
    
    is_recovered: bool = Field(False, description="Whether this order was saved through recovery intervention.")
    recovered_revenue: Decimal = Field(Decimal("0.00"), description="Recovered order transaction value.")
    
    provenance: EventProvenance

    @classmethod
    def validate_integrity(cls, baseline: Decimal, incremental: Decimal, total: Decimal) -> bool:
        """Sanity check: baseline + incremental should equal total net merchandise value before independent recovery attribution."""
        return (baseline + incremental) == total
