from decimal import Decimal

DEMO_MERCHANT = {
    "name": "Revora Athletics & Lifestyle",
    "slug": "revora-athletics",
    "currency": "INR",
    "is_active": True,
    "settings": {
        "theme": "dark",
        "contact_email": "merchant@revora.ai",
        "store_domain": "store.revora.ai",
    }
}

DEMO_CATEGORIES = [
    {
        "name": "Footwear & Running",
        "slug": "footwear-running",
        "description": "High-performance running, training, and marathon shoes.",
        "icon_name": "Footprints",
        "is_active": True,
    },
    {
        "name": "Apparel & Activewear",
        "slug": "apparel-activewear",
        "description": "Sweat-wicking, breathable athletic shirts, shorts, and tights.",
        "icon_name": "Shirt",
        "is_active": True,
    },
    {
        "name": "Accessories & Gear",
        "slug": "accessories-gear",
        "description": "Running socks, headbands, insulated bottles, and running belts.",
        "icon_name": "Sparkles",
        "is_active": True,
    },
    {
        "name": "Electronics & Wearables",
        "slug": "electronics-wearables",
        "description": "Fitness trackers, GPS watches, and wireless audio gear.",
        "icon_name": "Watch",
        "is_active": True,
    },
    {
        "name": "Nutrition & Recovery",
        "slug": "nutrition-recovery",
        "description": "Electrolytes, protein blends, and muscle recovery tools.",
        "icon_name": "Activity",
        "is_active": True,
    },
]

DEMO_PRODUCTS = [
    # =========================================================================
    # 1. Footwear & Running (20 products: REV-SHOE-01 to REV-SHOE-20)
    # =========================================================================
    {
        "sku": "REV-SHOE-01",
        "name": "Velocity Nitro Running Shoes",
        "description": "Engineered for speed, durability, and daily high-mileage runs with responsive nitrogen-infused foam cushioning.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("2499.00"),
        "cost_price": Decimal("1100.00"),
        "stock_quantity": 85,
        "image_url": "/images/products/footwear/velocity-nitro-running-shoes.svg",
        "tags": ["running", "shoes", "daily_trainer", "responsive", "cushion"],
        "metadata_json": {"weight": "235g", "drop": "8mm", "terrain": "Road", "cushion": "High"},
    },
    {
        "sku": "REV-SHOE-02",
        "name": "Apex Carbon Marathon Racer",
        "description": "Full-length carbon fiber propulsion plate with ultra-light PEBA foam for marathon PRs and tempo racing.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("3899.00"),
        "cost_price": Decimal("1750.00"),
        "stock_quantity": 40,
        "image_url": "/images/products/footwear/apex-carbon-marathon-racer.svg",
        "tags": ["marathon", "carbon_plate", "racing", "lightweight"],
        "metadata_json": {"weight": "190g", "drop": "6mm", "terrain": "Road/Track", "plate": "Full Carbon"},
    },
    {
        "sku": "REV-SHOE-03",
        "name": "CloudStride Ultra Distance Trainers",
        "description": "Maximum cushion recovery road running shoe with dual-layer midsole engineered for 20km+ training blocks.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("2899.00"),
        "cost_price": Decimal("1300.00"),
        "stock_quantity": 65,
        "image_url": "/images/products/footwear/cloudstride-ultra-distance-trainers.svg",
        "tags": ["max_cushion", "long_run", "recovery", "comfort"],
        "metadata_json": {"weight": "270g", "drop": "10mm", "terrain": "Road", "support": "Neutral"},
    },
    {
        "sku": "REV-SHOE-04",
        "name": "TrailGrip All-Terrain Summit Shoes",
        "description": "Aggressive 5mm Vibram multi-directional lugs and rock plate protection for rugged alpine single-tracks.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("3299.00"),
        "cost_price": Decimal("1450.00"),
        "stock_quantity": 50,
        "image_url": "/images/products/footwear/trailgrip-all-terrain-summit-shoes.svg",
        "tags": ["trail", "grip", "all_terrain", "rock_plate", "outdoors"],
        "metadata_json": {"weight": "295g", "drop": "4mm", "terrain": "Trail/Mud/Rock", "lug_depth": "5mm"},
    },
    {
        "sku": "REV-SHOE-05",
        "name": "SprintGlide Lightweight Tempo Shoes",
        "description": "Featherlight training flat built for speed intervals, 5K pace sessions, and track workouts.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("2799.00"),
        "cost_price": Decimal("1200.00"),
        "stock_quantity": 45,
        "image_url": "/images/products/footwear/sprintglide-lightweight-tempo-shoes.svg",
        "tags": ["speed", "tempo", "lightweight", "track", "intervals"],
        "metadata_json": {"weight": "185g", "drop": "5mm", "terrain": "Road/Track"},
    },
    {
        "sku": "REV-SHOE-06",
        "name": "HydroShield Waterproof Trail Runners",
        "description": "GORE-TEX membrane lining with high-traction rubber outsole for rainy day runs and snowy winter trails.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("3199.00"),
        "cost_price": Decimal("1400.00"),
        "stock_quantity": 35,
        "image_url": "/images/products/footwear/hydroshield-waterproof-trail-runners.svg",
        "tags": ["waterproof", "goretex", "trail", "winter", "rain"],
        "metadata_json": {"membrane": "GORE-TEX", "weight": "310g", "terrain": "Wet Trail"},
    },
    {
        "sku": "REV-SHOE-07",
        "name": "AeroStep Gym & Cross-Training Shoes",
        "description": "Wide flat base with lateral TPU stabilizers designed for weightlifting, HIIT, box jumps, and agility drills.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("2199.00"),
        "cost_price": Decimal("950.00"),
        "stock_quantity": 70,
        "image_url": "/images/products/footwear/aerostep-gym-and-cross-training-shoes.svg",
        "tags": ["cross_training", "gym", "hiit", "lifting", "stability"],
        "metadata_json": {"weight": "280g", "drop": "4mm", "stability": "High"},
    },
    {
        "sku": "REV-SHOE-08",
        "name": "EchoGlide Natural Motion Shoes",
        "description": "Zero-drop wide toe box construction encouraging natural foot splay, barefoot mechanics, and ankle strength.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("1999.00"),
        "cost_price": Decimal("850.00"),
        "stock_quantity": 55,
        "image_url": "/images/products/footwear/echoglide-natural-motion-shoes.svg",
        "tags": ["barefoot", "zero_drop", "natural", "wide_toe_box"],
        "metadata_json": {"drop": "0mm", "stack_height": "12mm", "weight": "175g"},
    },
    {
        "sku": "REV-SHOE-09",
        "name": "EnduraMax Long Run Road Shoes",
        "description": "Plush rocker geometry promoting smooth heel-to-toe transitions over grueling 30km marathon preparation runs.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("3499.00"),
        "cost_price": Decimal("1500.00"),
        "stock_quantity": 60,
        "image_url": "/images/products/footwear/enduramax-long-run-road-shoes.svg",
        "tags": ["long_run", "endurance", "cushion", "rocker"],
        "metadata_json": {"weight": "260g", "drop": "8mm", "rocker": "Active Glide"},
    },
    {
        "sku": "REV-SHOE-10",
        "name": "TempoFlex Responsive Daily Trainers",
        "description": "Versatile all-around trainer combining bounce and stability for 5K to half-marathon distances.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("2599.00"),
        "cost_price": Decimal("1150.00"),
        "stock_quantity": 75,
        "image_url": "/images/products/footwear/tempoflex-responsive-daily-trainers.svg",
        "tags": ["daily", "versatile", "responsive", "training"],
        "metadata_json": {"weight": "240g", "drop": "8mm", "midsole": "BioFoam Plus"},
    },
    {
        "sku": "REV-SHOE-11",
        "name": "PaceLite Beginner Athletic Running Shoes",
        "description": "Approachable comfort-first runner with supportive heel collar and breathable mesh for new runners.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("1799.00"),
        "cost_price": Decimal("750.00"),
        "stock_quantity": 90,
        "image_url": "/images/products/footwear/pacelite-beginner-athletic-running-shoes.svg",
        "tags": ["beginner", "budget", "breathable", "comfort"],
        "metadata_json": {"weight": "250g", "drop": "10mm", "fit": "Standard Comfort"},
    },
    {
        "sku": "REV-SHOE-12",
        "name": "MarathonPro Carbon Elite Racers",
        "description": "Championship racing shoe with supercritical foam and spoon-curved carbon plate for record-breaking speed.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("4999.00"),
        "cost_price": Decimal("2200.00"),
        "stock_quantity": 30,
        "image_url": "/images/products/footwear/marathonpro-carbon-elite-racers.svg",
        "tags": ["elite", "carbon", "racing", "podium"],
        "metadata_json": {"weight": "178g", "drop": "8mm", "plate": "Curved Carbon"},
    },
    {
        "sku": "REV-SHOE-13",
        "name": "StridePro Carbon Plate Racer",
        "description": "Dynamic carbon composite plate with high-energy PEBAX foam designed for half-marathon and 10K racing.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("4299.00"),
        "cost_price": Decimal("1900.00"),
        "stock_quantity": 40,
        "image_url": "/images/products/footwear/stridepro-carbon-plate-racer.svg",
        "tags": ["carbon_plate", "racing", "speed", "pebax"],
        "metadata_json": {"weight": "188g", "drop": "6mm", "terrain": "Road"},
    },
    {
        "sku": "REV-SHOE-14",
        "name": "VoltTrail Mountain Rugged Runner",
        "description": "Heavy-duty reinforced toe cap with dual-compound sticky rubber outsoles for rocky mountain terrain.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("3599.00"),
        "cost_price": Decimal("1600.00"),
        "stock_quantity": 50,
        "image_url": "/images/products/footwear/volttrail-mountain-rugged-runner.svg",
        "tags": ["mountain", "trail", "rugged", "protection"],
        "metadata_json": {"weight": "310g", "drop": "6mm", "lug_depth": "6mm"},
    },
    {
        "sku": "REV-SHOE-15",
        "name": "AeroStride Breathable Tempo Flats",
        "description": "Ultra-light breathable engineered mono-mesh racing flat with high ground feel for sprint intervals.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("2699.00"),
        "cost_price": Decimal("1150.00"),
        "stock_quantity": 60,
        "image_url": "/images/products/footwear/aerostride-breathable-tempo-flats.svg",
        "tags": ["tempo", "flats", "intervals", "lightweight"],
        "metadata_json": {"weight": "170g", "drop": "4mm", "terrain": "Road/Track"},
    },
    {
        "sku": "REV-SHOE-16",
        "name": "WaveCushion High-Arch Road Shoes",
        "description": "Structured dual-density arch bridge providing targeted medial support for overpronation control.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("3099.00"),
        "cost_price": Decimal("1350.00"),
        "stock_quantity": 55,
        "image_url": "/images/products/footwear/wavecushion-high-arch-road-shoes.svg",
        "tags": ["stability", "arch_support", "overpronation", "cushion"],
        "metadata_json": {"weight": "275g", "drop": "10mm", "support": "Stability"},
    },
    {
        "sku": "REV-SHOE-17",
        "name": "ApexGrip Mud & Wet Trail Shoes",
        "description": "Hydrophobic upper with deep self-cleaning 6mm chevron lugs engineered for wet mud and technical bogs.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("3399.00"),
        "cost_price": Decimal("1480.00"),
        "stock_quantity": 45,
        "image_url": "/images/products/footwear/apexgrip-mud-and-wet-trail-shoes.svg",
        "tags": ["mud", "trail", "grip", "wet_weather"],
        "metadata_json": {"weight": "290g", "drop": "5mm", "lugs": "6mm Chevron"},
    },
    {
        "sku": "REV-SHOE-18",
        "name": "SwiftStep Lightweight 10K Trainers",
        "description": "Agile responsive daily mileage shoe tuned for brisk 5K and 10K training runs.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("2299.00"),
        "cost_price": Decimal("980.00"),
        "stock_quantity": 80,
        "image_url": "/images/products/footwear/swiftstep-lightweight-10k-trainers.svg",
        "tags": ["10k", "speed", "trainer", "responsive"],
        "metadata_json": {"weight": "215g", "drop": "8mm", "terrain": "Road"},
    },
    {
        "sku": "REV-SHOE-19",
        "name": "EnduranceFlow Maximum Stability Shoes",
        "description": "Guide-rail stabilization system reducing excess ankle rotation during high-volume marathon blocks.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("2999.00"),
        "cost_price": Decimal("1300.00"),
        "stock_quantity": 65,
        "image_url": "/images/products/footwear/enduranceflow-maximum-stability-shoes.svg",
        "tags": ["stability", "guide_rails", "endurance", "marathon"],
        "metadata_json": {"weight": "285g", "drop": "8mm", "support": "Max Stability"},
    },
    {
        "sku": "REV-SHOE-20",
        "name": "UltraMarathon PEBA Superfoam Racers",
        "description": "Premium ultra-distance racing shoe packed with maximum legal 40mm stack height supercritical superfoam.",
        "category": "Footwear & Running",
        "category_slug": "footwear-running",
        "price": Decimal("4799.00"),
        "cost_price": Decimal("2100.00"),
        "stock_quantity": 35,
        "image_url": "/images/products/footwear/ultramarathon-peba-superfoam-racers.svg",
        "tags": ["superfoam", "ultramarathon", "peba", "stack_height"],
        "metadata_json": {"weight": "198g", "drop": "8mm", "stack_height": "40mm"},
    },

    # =========================================================================
    # 2. Apparel & Activewear (20 products: REV-APP-01 to REV-APP-20)
    # =========================================================================
    {
        "sku": "REV-APP-01",
        "name": "AeroVent Pro Seamless Running Tee",
        "description": "Ultra-lightweight micro-mesh fabric with body-mapped ventilation zones and anti-chafe flatlock seams.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("799.00"),
        "cost_price": Decimal("300.00"),
        "stock_quantity": 120,
        "image_url": "/images/products/apparel/aerovent-pro-seamless-running-tee.svg",
        "tags": ["tshirt", "seamless", "running", "anti_chafe", "ventilation"],
        "metadata_json": {"material": "88% Recycled Poly, 12% Spandex", "weight": "95g"},
    },
    {
        "sku": "REV-APP-02",
        "name": "Endurance 2-in-1 Compression Shorts",
        "description": "Built-in 5-inch supportive compression liner with bounce-free zippered phone pocket and side gel loops.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("899.00"),
        "cost_price": Decimal("350.00"),
        "stock_quantity": 110,
        "image_url": "/images/products/apparel/endurance-2-in-1-compression-shorts.svg",
        "tags": ["shorts", "compression", "2in1", "pockets", "marathon"],
        "metadata_json": {"inseam": "5 inch", "liner": "Compression", "pockets": 3},
    },
    {
        "sku": "REV-APP-03",
        "name": "ThermalShield Packable Windbreaker",
        "description": "Windproof and DWR water-resistant running jacket that packs into its own chest pocket with reflective trims.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1499.00"),
        "cost_price": Decimal("600.00"),
        "stock_quantity": 75,
        "image_url": "/images/products/apparel/thermalshield-packable-windbreaker.svg",
        "tags": ["jacket", "windbreaker", "packable", "reflective", "water_resistant"],
        "metadata_json": {"packable": True, "weight": "110g", "dwr_rating": "Level 4"},
    },
    {
        "sku": "REV-APP-04",
        "name": "CoreFlex High-Waist Athletic Leggings",
        "description": "Squat-proof 4-way stretch fabric with graduated abdominal compression and dual deep drop-in side pockets.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1199.00"),
        "cost_price": Decimal("480.00"),
        "stock_quantity": 95,
        "image_url": "/images/products/apparel/coreflex-high-waist-athletic-leggings.svg",
        "tags": ["leggings", "tights", "compression", "yoga", "running"],
        "metadata_json": {"waistband": "High-rise", "opacity": "100% Squat Proof"},
    },
    {
        "sku": "REV-APP-05",
        "name": "HydroDry Sleeveless Marathon Singlet",
        "description": "Featherlight competition racing singlet engineered to wick sweat rapidly in hot summer marathons.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("699.00"),
        "cost_price": Decimal("250.00"),
        "stock_quantity": 130,
        "image_url": "/images/products/apparel/hydrodry-sleeveless-marathon-singlet.svg",
        "tags": ["singlet", "racing", "summer", "breathable"],
        "metadata_json": {"weight": "65g", "fit": "Athletic Race Cut"},
    },
    {
        "sku": "REV-APP-06",
        "name": "StormFlex Half-Zip Winter Layer",
        "description": "Brushed thermal grid fleece with thumbholes and watch window for cold morning winter training runs.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1299.00"),
        "cost_price": Decimal("520.00"),
        "stock_quantity": 80,
        "image_url": "/images/products/apparel/stormflex-half-zip-winter-layer.svg",
        "tags": ["half_zip", "winter", "thermal", "fleece"],
        "metadata_json": {"features": "Watch Window, Thumbholes", "warmth": "Mid-weight"},
    },
    {
        "sku": "REV-APP-07",
        "name": "ImpactFit Medium-Support Sports Bra",
        "description": "Encapsulated support sports bra with moisture-wicking underband and breathable racerback mesh panel.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("749.00"),
        "cost_price": Decimal("290.00"),
        "stock_quantity": 90,
        "image_url": "/images/products/apparel/impactfit-medium-support-sports-bra.svg",
        "tags": ["sports_bra", "support", "running", "fitness"],
        "metadata_json": {"support_level": "Medium-High", "cups": "Removable"},
    },
    {
        "sku": "REV-APP-08",
        "name": "SwiftMotion Track Training Joggers",
        "description": "Tapered athletic pants with ankle zips for easy on/off over running shoes and secure zippered pockets.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1099.00"),
        "cost_price": Decimal("440.00"),
        "stock_quantity": 85,
        "image_url": "/images/products/apparel/swiftmotion-track-training-joggers.svg",
        "tags": ["joggers", "track_pants", "warmup", "gym"],
        "metadata_json": {"fit": "Tapered Slim", "zippers": "YKK Ankle Zips"},
    },
    {
        "sku": "REV-APP-09",
        "name": "AeroDry Ultra-Lightweight Training Singlet",
        "description": "Minimalist singlet with laser-cut ventilation holes across the back for maximum evaporative cooling.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("649.00"),
        "cost_price": Decimal("240.00"),
        "stock_quantity": 100,
        "image_url": "/images/products/apparel/aerodry-ultra-lightweight-training-singlet.svg",
        "tags": ["singlet", "cooling", "training", "summer"],
        "metadata_json": {"cooling": "Active Air Flow", "weight": "70g"},
    },
    {
        "sku": "REV-APP-10",
        "name": "Velocity Compression Training Tights",
        "description": "Full-length graduated compression tights supporting quadriceps and calves during high-intensity training.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1399.00"),
        "cost_price": Decimal("580.00"),
        "stock_quantity": 70,
        "image_url": "/images/products/apparel/velocity-compression-training-tights.svg",
        "tags": ["compression", "tights", "muscle_support", "recovery"],
        "metadata_json": {"compression": "15-20 mmHg", "length": "Full Length"},
    },
    {
        "sku": "REV-APP-11",
        "name": "ThermalRun Merino Wool Base Layer",
        "description": "100% natural Merino wool long sleeve offering odor resistance, moisture control, and natural thermal insulation.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1599.00"),
        "cost_price": Decimal("700.00"),
        "stock_quantity": 55,
        "image_url": "/images/products/apparel/thermalrun-merino-wool-base-layer.svg",
        "tags": ["merino", "base_layer", "wool", "odor_resistant"],
        "metadata_json": {"material": "100% Merino Wool 200gsm"},
    },
    {
        "sku": "REV-APP-12",
        "name": "RecoveryFlex Post-Run Pullover Hoodie",
        "description": "Heavyweight French terry pullover with generous hood and kangaroo pocket for post-workout cool-down.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1799.00"),
        "cost_price": Decimal("790.00"),
        "stock_quantity": 65,
        "image_url": "/images/products/apparel/recoveryflex-post-run-pullover-hoodie.svg",
        "tags": ["hoodie", "recovery", "cotton", "lifestyle"],
        "metadata_json": {"material": "100% French Terry Cotton 380gsm"},
    },
    {
        "sku": "REV-APP-13",
        "name": "HyperVent Reflective Race Singlet",
        "description": "Laser-perforated racing singlet featuring 360-degree reflective micro-dots for dusk and dawn visibility.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("749.00"),
        "cost_price": Decimal("280.00"),
        "stock_quantity": 115,
        "image_url": "/images/products/apparel/hypervent-reflective-race-singlet.svg",
        "tags": ["singlet", "reflective", "racing", "high_viz"],
        "metadata_json": {"weight": "68g", "reflectivity": "360 Degree"},
    },
    {
        "sku": "REV-APP-14",
        "name": "AeroKnit Long-Sleeve Sun Hoodie",
        "description": "UPF 50+ ultralight sun protection hoodie with fitted scuba hood for long exposed trail expeditions.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1399.00"),
        "cost_price": Decimal("560.00"),
        "stock_quantity": 80,
        "image_url": "/images/products/apparel/aeroknit-long-sleeve-sun-hoodie.svg",
        "tags": ["sun_hoodie", "upf50", "trail", "protection"],
        "metadata_json": {"upf_rating": "50+", "fabric": "AeroKnit Poly"},
    },
    {
        "sku": "REV-APP-15",
        "name": "ProStretch 7-Inch Trail Cargo Shorts",
        "description": "Durable stretch ripstop trail shorts equipped with 4 mesh nutrition pockets and zippered key storage.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("949.00"),
        "cost_price": Decimal("380.00"),
        "stock_quantity": 90,
        "image_url": "/images/products/apparel/prostretch-7-inch-trail-cargo-shorts.svg",
        "tags": ["trail_shorts", "cargo", "pockets", "ripstop"],
        "metadata_json": {"inseam": "7 inch", "pockets": 5},
    },
    {
        "sku": "REV-APP-16",
        "name": "ThermaGrid High-Neck Running Pullover",
        "description": "Insulating grid fleece pullover with deep venting front zipper and integrated watch pass-through cuffs.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1449.00"),
        "cost_price": Decimal("600.00"),
        "stock_quantity": 70,
        "image_url": "/images/products/apparel/thermagrid-high-neck-running-pullover.svg",
        "tags": ["winter", "pullover", "fleece", "cold_weather"],
        "metadata_json": {"warmth": "High Thermal", "fabric": "ThermaGrid 240g"},
    },
    {
        "sku": "REV-APP-17",
        "name": "SpeedMesh Athletic Quarter-Zip Top",
        "description": "Aerodynamic quarter-zip midlayer with breathable mesh underarm inserts for temperature regulation.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1199.00"),
        "cost_price": Decimal("490.00"),
        "stock_quantity": 85,
        "image_url": "/images/products/apparel/speedmesh-athletic-quarter-zip-top.svg",
        "tags": ["quarter_zip", "midlayer", "training", "aerodynamic"],
        "metadata_json": {"zipper": "Locking YKK", "mesh_panels": "Underarm & Back"},
    },
    {
        "sku": "REV-APP-18",
        "name": "CoreStability High-Rise Compression Shorts",
        "description": "Targeted pelvic and hamstring compression shorts providing core stabilization during tempo efforts.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("849.00"),
        "cost_price": Decimal("340.00"),
        "stock_quantity": 105,
        "image_url": "/images/products/apparel/corestability-high-rise-compression-shorts.svg",
        "tags": ["compression", "core_support", "hamstring", "training"],
        "metadata_json": {"waist": "Wide High-Rise", "compression": "Firm"},
    },
    {
        "sku": "REV-APP-19",
        "name": "WeatherShield DWR Running Anorak",
        "description": "Ultralight half-zip storm shell with storm-proof taped seams and adjustable bungee hem.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1699.00"),
        "cost_price": Decimal("720.00"),
        "stock_quantity": 60,
        "image_url": "/images/products/apparel/weathershield-dwr-running-anorak.svg",
        "tags": ["anorak", "rain_jacket", "waterproof", "storm"],
        "metadata_json": {"waterproofing": "10000mm", "weight": "130g"},
    },
    {
        "sku": "REV-APP-20",
        "name": "AeroSeamless Marathon Racing Tights",
        "description": "3D circular knit seamless long tights designed to eliminate all friction points during 42.2km races.",
        "category": "Apparel & Activewear",
        "category_slug": "apparel-activewear",
        "price": Decimal("1499.00"),
        "cost_price": Decimal("630.00"),
        "stock_quantity": 75,
        "image_url": "/images/products/apparel/aeroseamless-marathon-racing-tights.svg",
        "tags": ["seamless", "marathon_tights", "friction_free", "racing"],
        "metadata_json": {"knit": "3D Circular Knit", "fit": "Second-skin"},
    },

    # =========================================================================
    # 3. Accessories & Gear (20 products: REV-SOCK-01, REV-HEAD-01, ... REV-ACC-20)
    # =========================================================================
    {
        "sku": "REV-SOCK-01",
        "name": "Breathable Sports Cushion Socks (3-Pack)",
        "description": "Ergonomic arch compression, anti-blister yarn, and reinforced heel/toe padding designed specifically for runners.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("299.00"),
        "cost_price": Decimal("90.00"),
        "stock_quantity": 250,
        "image_url": "/images/products/accessories/breathable-sports-cushion-socks-3-pack.svg",
        "tags": ["socks", "cushion", "anti_blister", "running", "essential"],
        "metadata_json": {"pack_size": 3, "material": "CoolMax Nylon Blend", "arch_support": True},
    },
    {
        "sku": "REV-HEAD-01",
        "name": "Sweat-Wicking Performance Headband",
        "description": "Non-slip silicone grip lining stops sweat from dripping into eyes during intense high-humidity tempo sessions.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("199.00"),
        "cost_price": Decimal("60.00"),
        "stock_quantity": 200,
        "image_url": "/images/products/accessories/sweat-wicking-performance-headband.svg",
        "tags": ["headband", "sweat", "grip", "running"],
        "metadata_json": {"width": "2.5 Inches", "grip": "Medical Silicone"},
    },
    {
        "sku": "REV-VEST-01",
        "name": "TrailRunner Hydration Vest (5L)",
        "description": "Ergonomic bounce-free trail vest with twin 500ml soft flask holders and rear zippered storage.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("1499.00"),
        "cost_price": Decimal("650.00"),
        "stock_quantity": 60,
        "image_url": "/images/products/accessories/trailrunner-hydration-vest-5l.svg",
        "tags": ["hydration", "vest", "trail", "backpack"],
        "metadata_json": {"capacity": "5 Liters", "flasks_included": "2x 500ml"},
    },
    {
        "sku": "REV-BOTTLE-01",
        "name": "Insulated Stainless Steel Sports Bottle (750ml)",
        "description": "Double-wall vacuum insulation keeping ice water cold for 24 hours with one-touch sport lid.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("599.00"),
        "cost_price": Decimal("220.00"),
        "stock_quantity": 180,
        "image_url": "/images/products/accessories/insulated-stainless-steel-sports-bottle-750ml.svg",
        "tags": ["bottle", "hydration", "insulated", "gym"],
        "metadata_json": {"volume": "750ml", "material": "18/8 Pro Grade Stainless Steel"},
    },
    {
        "sku": "REV-BELT-01",
        "name": "No-Bounce Ultra Slim Running Belt",
        "description": "Expandable Lycra waist pack fitting large smartphones, energy gels, and keys without bouncing.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("399.00"),
        "cost_price": Decimal("130.00"),
        "stock_quantity": 220,
        "image_url": "/images/products/accessories/no-bounce-ultra-slim-running-belt.svg",
        "tags": ["running_belt", "waistpack", "phone_holder"],
        "metadata_json": {"water_resistant": True, "reflective": True},
    },
    {
        "sku": "REV-CAP-01",
        "name": "Laser-Vent UV Protection Running Cap",
        "description": "UPF 50+ sun protection cap with dark underbill reducing glare and moisture-wicking headband.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("449.00"),
        "cost_price": Decimal("160.00"),
        "stock_quantity": 140,
        "image_url": "/images/products/accessories/laser-vent-uv-protection-running-cap.svg",
        "tags": ["cap", "sun_protection", "running", "hat"],
        "metadata_json": {"upf_rating": "50+", "weight": "45g"},
    },
    {
        "sku": "REV-GLOVE-01",
        "name": "Touchscreen Winter Running Gloves",
        "description": "Thermal wind-resistant gloves with conductive fingertips allowing phone screen operation.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("499.00"),
        "cost_price": Decimal("180.00"),
        "stock_quantity": 90,
        "image_url": "/images/products/accessories/touchscreen-winter-running-gloves.svg",
        "tags": ["gloves", "touchscreen", "winter", "thermal"],
        "metadata_json": {"touchscreen_compatible": True, "grip": "Silicone Palm"},
    },
    {
        "sku": "REV-SLEEVE-01",
        "name": "Graduated Compression Calf Sleeves (Pair)",
        "description": "20-30 mmHg medical grade graduated compression improving blood circulation and reducing shin splints.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("549.00"),
        "cost_price": Decimal("190.00"),
        "stock_quantity": 115,
        "image_url": "/images/products/accessories/graduated-compression-calf-sleeves-pair.svg",
        "tags": ["compression", "calf_sleeves", "shin_splints", "recovery"],
        "metadata_json": {"pressure": "20-30 mmHg", "sizes": ["M", "L"]},
    },
    {
        "sku": "REV-LACE-01",
        "name": "SpeedLock Reflective Elastic Shoe Laces",
        "description": "Zero-tie elastic lock shoelaces providing consistent tension and rapid triathlon transitions.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("199.00"),
        "cost_price": Decimal("50.00"),
        "stock_quantity": 300,
        "image_url": "/images/products/accessories/speedlock-reflective-elastic-shoe-laces.svg",
        "tags": ["laces", "lock_laces", "triathlon", "reflective"],
        "metadata_json": {"length": "120cm", "lock_mechanism": "Spring Push Button"},
    },
    {
        "sku": "REV-BAND-01",
        "name": "NightGlow High-Visibility LED Armband",
        "description": "Rechargeable 360-degree LED running safety band with flashing and continuous glow modes.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("249.00"),
        "cost_price": Decimal("75.00"),
        "stock_quantity": 170,
        "image_url": "/images/products/accessories/nightglow-high-visibility-led-armband.svg",
        "tags": ["safety", "led", "night_running", "visibility"],
        "metadata_json": {"battery": "USB Rechargeable 10h", "waterproof": "IPX4"},
    },
    {
        "sku": "REV-TOWEL-01",
        "name": "QuickDry Microfiber Sports Sweat Towel",
        "description": "Compact antimicrobial microfiber towel absorbing 4x its weight in water and drying in 15 minutes.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("299.00"),
        "cost_price": Decimal("90.00"),
        "stock_quantity": 210,
        "image_url": "/images/products/accessories/quickdry-microfiber-sports-sweat-towel.svg",
        "tags": ["towel", "microfiber", "gym", "quick_dry"],
        "metadata_json": {"size": "80cm x 40cm", "antimicrobial": True},
    },
    {
        "sku": "REV-DUFFEL-01",
        "name": "Endurance Ventilated Gym & Race Duffel (35L)",
        "description": "Water-resistant training duffel featuring dedicated ventilated shoe compartment and wet/dry divider.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("1699.00"),
        "cost_price": Decimal("750.00"),
        "stock_quantity": 55,
        "image_url": "/images/products/accessories/endurance-ventilated-gym-and-race-duffel-35l.svg",
        "tags": ["duffel", "gym_bag", "shoe_compartment", "travel"],
        "metadata_json": {"volume": "35 Liters", "shoe_pocket": True, "water_resistant": True},
    },
    {
        "sku": "REV-ACC-13",
        "name": "UltraGrip Athletic Training Gloves",
        "description": "Reinforced microfiber palm gloves with silicone micro-texture for barbells, pull-ups, and calisthenics.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("449.00"),
        "cost_price": Decimal("160.00"),
        "stock_quantity": 120,
        "image_url": "/images/products/accessories/ultragrip-athletic-training-gloves.svg",
        "tags": ["gloves", "grip", "lifting", "gym"],
        "metadata_json": {"palm": "Silicone HexGrip", "wrist_wrap": "Elastic Velcro"},
    },
    {
        "sku": "REV-ACC-14",
        "name": "SpeedHydrate Handheld Running Bottle (500ml)",
        "description": "Ergonomic handheld bottle with cinch-strap handle and quick-burst high-flow bite valve.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("399.00"),
        "cost_price": Decimal("140.00"),
        "stock_quantity": 160,
        "image_url": "/images/products/accessories/speedhydrate-handheld-running-bottle-500ml.svg",
        "tags": ["handheld_bottle", "hydration", "running", "bite_valve"],
        "metadata_json": {"capacity": "500ml", "bpa_free": True},
    },
    {
        "sku": "REV-ACC-15",
        "name": "AeroVisor Lightweight Sun Shield",
        "description": "Open-top ultralight athletic visor delivering maximum head heat dissipation and sun shade.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("349.00"),
        "cost_price": Decimal("120.00"),
        "stock_quantity": 130,
        "image_url": "/images/products/accessories/aerovisor-lightweight-sun-shield.svg",
        "tags": ["visor", "sun_shield", "running", "summer"],
        "metadata_json": {"weight": "32g", "strap": "Adjustable Elastic"},
    },
    {
        "sku": "REV-ACC-16",
        "name": "Reflective 3M Hi-Viz Running Sash",
        "description": "Ultra-bright 3M Scotchlite reflective crossed sash offering 500-meter car headlight illumination.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("249.00"),
        "cost_price": Decimal("80.00"),
        "stock_quantity": 190,
        "image_url": "/images/products/accessories/reflective-3m-hi-viz-running-sash.svg",
        "tags": ["reflective", "hi_viz", "safety", "night"],
        "metadata_json": {"standard": "EN ISO 20471", "visibility_range": "500m"},
    },
    {
        "sku": "REV-ACC-17",
        "name": "Triathlon Magnetic Race Bib Belt",
        "description": "Elastic race number belt with strong magnetic toggles that attach race bibs without safety pins.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("299.00"),
        "cost_price": Decimal("95.00"),
        "stock_quantity": 210,
        "image_url": "/images/products/accessories/triathlon-magnetic-race-bib-belt.svg",
        "tags": ["race_belt", "bib_holder", "triathlon", "marathon"],
        "metadata_json": {"magnets": "4x Neodymium", "gel_loops": 6},
    },
    {
        "sku": "REV-ACC-18",
        "name": "Silicone Soft Collapsible Flask (500ml)",
        "description": "Collapsible TPU flask that shrinks as you drink to minimize liquid sloshing in hydration vests.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("349.00"),
        "cost_price": Decimal("120.00"),
        "stock_quantity": 175,
        "image_url": "/images/products/accessories/silicone-soft-collapsible-flask-500ml.svg",
        "tags": ["soft_flask", "hydration", "collapsible", "trail"],
        "metadata_json": {"material": "100% BPA/PVC Free TPU", "capacity": "500ml"},
    },
    {
        "sku": "REV-ACC-19",
        "name": "Waterproof Armband Phone Holder",
        "description": "Sweatproof clear-window touch-sensitive armband keeping modern large smartphones secure.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("499.00"),
        "cost_price": Decimal("170.00"),
        "stock_quantity": 140,
        "image_url": "/images/products/accessories/waterproof-armband-phone-holder.svg",
        "tags": ["armband", "phone_holder", "touchscreen", "waterproof"],
        "metadata_json": {"phone_size": "Up to 6.8 Inches", "waterproof": "IPX6"},
    },
    {
        "sku": "REV-ACC-20",
        "name": "AeroSpeed Anti-Chafe Body Glide Balm",
        "description": "All-natural moisture-resistant anti-friction glide stick preventing blister and chafing hot spots.",
        "category": "Accessories & Gear",
        "category_slug": "accessories-gear",
        "price": Decimal("399.00"),
        "cost_price": Decimal("130.00"),
        "stock_quantity": 200,
        "image_url": "/images/products/accessories/aerospeed-anti-chafe-body-glide-balm.svg",
        "tags": ["anti_chafe", "body_glide", "blister_prevention", "skin_care"],
        "metadata_json": {"net_wt": "75g", "formula": "Plant-based Beeswax & Aloe"},
    },

    # =========================================================================
    # 4. Electronics & Wearables (20 products: REV-TECH-01 to REV-TECH-20)
    # =========================================================================
    {
        "sku": "REV-TECH-01",
        "name": "PulseTrack Pro GPS Sports Watch",
        "description": "Multi-band GNSS GPS watch with wrist-based running power, VO2 max tracking, and 14-day battery life.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("3499.00"),
        "cost_price": Decimal("1600.00"),
        "stock_quantity": 50,
        "image_url": "/images/products/electronics/pulsetrack-pro-gps-sports-watch.svg",
        "tags": ["watch", "gps", "heart_rate", "vo2max", "wearable"],
        "metadata_json": {"battery_life": "14 Days", "water_rating": "5 ATM", "weight": "42g"},
    },
    {
        "sku": "REV-TECH-02",
        "name": "AeroBeats IPX7 Wireless Sport Earbuds",
        "description": "Secure over-ear hook earbuds with 32h playback, ambient awareness mode, and sweatproof titanium driver.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("1999.00"),
        "cost_price": Decimal("850.00"),
        "stock_quantity": 65,
        "image_url": "/images/products/electronics/aerobeats-ipx7-wireless-sport-earbuds.svg",
        "tags": ["earbuds", "wireless", "audio", "ipx7", "bluetooth"],
        "metadata_json": {"water_rating": "IPX7 Waterproof", "playtime": "32 Hours with Case"},
    },
    {
        "sku": "REV-TECH-03",
        "name": "AeroPulse Optical Armband Heart Rate Monitor",
        "description": "Precision multi-LED optical sensor broadcasting ANT+ and dual Bluetooth to fitness watches and cycling computers.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("1499.00"),
        "cost_price": Decimal("650.00"),
        "stock_quantity": 70,
        "image_url": "/images/products/electronics/aeropulse-optical-armband-heart-rate-monitor.svg",
        "tags": ["heart_rate", "sensor", "armband", "bluetooth", "ant+"],
        "metadata_json": {"connectivity": "BLE & ANT+", "battery": "Rechargeable 30h"},
    },
    {
        "sku": "REV-TECH-04",
        "name": "NightRunner High-Lumen Chest Light",
        "description": "250 lumen wide-angle beam chest light with red rear hazard flasher for safe nighttime road runs.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("799.00"),
        "cost_price": Decimal("320.00"),
        "stock_quantity": 90,
        "image_url": "/images/products/electronics/nightrunner-high-lumen-chest-light.svg",
        "tags": ["light", "safety", "night_running", "headlamp"],
        "metadata_json": {"lumens": "250 lm", "battery": "USB Rechargeable"},
    },
    {
        "sku": "REV-TECH-05",
        "name": "BoneConduction Open-Ear Audio Headset",
        "description": "Bone-conduction transducers delivering crystal clear music while keeping your ears open to traffic sounds.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("2499.00"),
        "cost_price": Decimal("1150.00"),
        "stock_quantity": 40,
        "image_url": "/images/products/electronics/boneconduction-open-ear-audio-headset.svg",
        "tags": ["bone_conduction", "open_ear", "audio", "safety"],
        "metadata_json": {"weight": "28g", "battery": "8 Hours"},
    },
    {
        "sku": "REV-TECH-06",
        "name": "SpeedCadence Bluetooth Running Pod",
        "description": "Shoe clip-on sensor transmitting cadence, stride length, ground contact time, and vertical oscillation.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("1199.00"),
        "cost_price": Decimal("500.00"),
        "stock_quantity": 45,
        "image_url": "/images/products/electronics/speedcadence-bluetooth-running-pod.svg",
        "tags": ["pod", "cadence", "dynamics", "running_tech"],
        "metadata_json": {"sensor_type": "3D Accelerometer", "battery": "CR2032 1-Year"},
    },
    {
        "sku": "REV-TECH-07",
        "name": "SmartJumper Digital Speed Jump Rope",
        "description": "Ball bearing jump rope with built-in LCD handle counting jumps, calories burned, and workout duration.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("649.00"),
        "cost_price": Decimal("240.00"),
        "stock_quantity": 110,
        "image_url": "/images/products/electronics/smartjumper-digital-speed-jump-rope.svg",
        "tags": ["jump_rope", "cardio", "smart_rope", "hiit"],
        "metadata_json": {"cable_length": "3m Adjustable", "display": "Backlit LCD"},
    },
    {
        "sku": "REV-TECH-08",
        "name": "StrideSense Foot Pod Cadence Tracker",
        "description": "Advanced gait analysis sensor recording pronation angle, impact shock force, and flight time.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("1299.00"),
        "cost_price": Decimal("550.00"),
        "stock_quantity": 50,
        "image_url": "/images/products/electronics/stridesense-foot-pod-cadence-tracker.svg",
        "tags": ["gait_analysis", "sensor", "foot_pod", "cadence"],
        "metadata_json": {"accuracy": "99.2%", "waterproof": "IP67"},
    },
    {
        "sku": "REV-TECH-09",
        "name": "CoreBeat Chest Strap Heart Rate Monitor",
        "description": "ECG-grade electrical chest strap transmitting accurate real-time heart rate and HRV data.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("1799.00"),
        "cost_price": Decimal("750.00"),
        "stock_quantity": 40,
        "image_url": "/images/products/electronics/corebeat-chest-strap-heart-rate-monitor.svg",
        "tags": ["ecg", "heart_rate", "chest_strap", "hrv"],
        "metadata_json": {"sensor": "Dual Lead ECG", "battery": "400 Hours"},
    },
    {
        "sku": "REV-TECH-10",
        "name": "TrailBeam Rechargeable Ultra Headlamp (400lm)",
        "description": "Lightweight 400 lumen trail running headlamp with red night-vision mode and tilting beam angle.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("899.00"),
        "cost_price": Decimal("380.00"),
        "stock_quantity": 80,
        "image_url": "/images/products/electronics/trailbeam-rechargeable-ultra-headlamp-400lm.svg",
        "tags": ["headlamp", "lumens", "trail", "night_running"],
        "metadata_json": {"lumens": "400 Lumens", "beam_distance": "80m"},
    },
    {
        "sku": "REV-TECH-11",
        "name": "SmartHydrate Bluetooth Water Intake Sensor",
        "description": "Smart bottle cap tracker monitoring daily fluid intake and flashing hydration reminders.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("999.00"),
        "cost_price": Decimal("420.00"),
        "stock_quantity": 60,
        "image_url": "/images/products/electronics/smarthydrate-bluetooth-water-intake-sensor.svg",
        "tags": ["hydration", "smart_sensor", "bluetooth", "tracking"],
        "metadata_json": {"sensor": "Optical Fluid Level", "app_sync": True},
    },
    {
        "sku": "REV-TECH-12",
        "name": "SprintTimer Digital Multi-Lap Interval Watch",
        "description": "Dedicated 100-lap memory stopwatch with countdown pacing beeper and water resistance for track coaches.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("1099.00"),
        "cost_price": Decimal("450.00"),
        "stock_quantity": 70,
        "image_url": "/images/products/electronics/sprinttimer-digital-multi-lap-interval-watch.svg",
        "tags": ["stopwatch", "interval", "track", "lap_timer"],
        "metadata_json": {"lap_memory": "100 Laps", "water_resistance": "50m"},
    },
    {
        "sku": "REV-TECH-13",
        "name": "AeroSound True Wireless Sport Pods",
        "description": "Active noise cancellation earbuds with punchy bass and hydrophobic nano-coating for intense gym sessions.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("2199.00"),
        "cost_price": Decimal("950.00"),
        "stock_quantity": 55,
        "image_url": "/images/products/electronics/aerosound-true-wireless-sport-pods.svg",
        "tags": ["earbuds", "anc", "wireless", "audio"],
        "metadata_json": {"battery": "28h Total", "waterproof": "IPX6"},
    },
    {
        "sku": "REV-TECH-14",
        "name": "PulseClip Mini ECG Heart Rate Sensor",
        "description": "Ultra-compact 12g sensor clipping onto sports bra or waistband for continuous athletic cardiac rhythm logging.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("1599.00"),
        "cost_price": Decimal("680.00"),
        "stock_quantity": 65,
        "image_url": "/images/products/electronics/pulseclip-mini-ecg-heart-rate-sensor.svg",
        "tags": ["ecg", "clip_sensor", "heart_rate", "compact"],
        "metadata_json": {"weight": "12g", "battery": "150 Hours"},
    },
    {
        "sku": "REV-TECH-15",
        "name": "SolarNav Dual-Frequency GPS Watch",
        "description": "Solar-assisted charging multisport smartwatch with topo maps, barometric altimeter, and turn-by-turn routing.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("4499.00"),
        "cost_price": Decimal("2000.00"),
        "stock_quantity": 30,
        "image_url": "/images/products/electronics/solarnav-dual-frequency-gps-watch.svg",
        "tags": ["solar", "gps", "navigation", "multisport"],
        "metadata_json": {"battery": "Solar Unlimited (Watch mode)", "maps": "Topo Preloaded"},
    },
    {
        "sku": "REV-TECH-16",
        "name": "NightSafety Magnetic Clip Strobe Light",
        "description": "Powerful magnetic dual-LED beacon clipping to shorts, vests, or caps for 360-degree night visibility.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("349.00"),
        "cost_price": Decimal("110.00"),
        "stock_quantity": 180,
        "image_url": "/images/products/electronics/nightsafety-magnetic-clip-strobe-light.svg",
        "tags": ["strobe", "safety_light", "magnetic", "visibility"],
        "metadata_json": {"modes": "Flash & Steady", "weight": "18g"},
    },
    {
        "sku": "REV-TECH-17",
        "name": "SmartFoot Kinetic Power Meter Pod",
        "description": "Direct-force running power meter computing wattage output, leg spring stiffness, and efficiency index.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("1899.00"),
        "cost_price": Decimal("820.00"),
        "stock_quantity": 40,
        "image_url": "/images/products/electronics/smartfoot-kinetic-power-meter-pod.svg",
        "tags": ["power_meter", "running_power", "wattage", "metrics"],
        "metadata_json": {"metric": "Running Watts", "accuracy": "+/- 1.5%"},
    },
    {
        "sku": "REV-TECH-18",
        "name": "AeroTrack Dual-Band Cycling Speed Sensor",
        "description": "Magnetless hub-mounted sensor recording exact wheel rotation speed for indoor trainers and outdoor bikes.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("899.00"),
        "cost_price": Decimal("360.00"),
        "stock_quantity": 75,
        "image_url": "/images/products/electronics/aerotrack-dual-band-cycling-speed-sensor.svg",
        "tags": ["speed_sensor", "cycling", "bluetooth", "ant+"],
        "metadata_json": {"mounting": "Hub Strap", "battery": "CR2032 300h"},
    },
    {
        "sku": "REV-TECH-19",
        "name": "ThermoSense Core Temperature Arm Sensor",
        "description": "Continuous core body temperature thermal sensor monitoring heat strain index during summer training.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("2299.00"),
        "cost_price": Decimal("980.00"),
        "stock_quantity": 35,
        "image_url": "/images/products/electronics/thermosense-core-temperature-arm-sensor.svg",
        "tags": ["temperature", "heat_strain", "sensor", "endurance"],
        "metadata_json": {"accuracy": "0.1 deg C", "waterproof": "IP68"},
    },
    {
        "sku": "REV-TECH-20",
        "name": "UltraBeam 600-Lumen Trail Headlamp",
        "description": "Extreme brightness trail ultra headlamp with reactive lighting sensors that auto-adjust beam strength.",
        "category": "Electronics & Wearables",
        "category_slug": "electronics-wearables",
        "price": Decimal("1199.00"),
        "cost_price": Decimal("500.00"),
        "stock_quantity": 60,
        "image_url": "/images/products/electronics/ultrabeam-600-lumen-trail-headlamp.svg",
        "tags": ["headlamp", "600lm", "reactive_lighting", "trail_ultra"],
        "metadata_json": {"lumens": "600 Lumens", "battery": "2400mAh Li-ion"},
    },

    # =========================================================================
    # 5. Nutrition & Recovery (20 products: REV-NUT-01 to REV-NUT-20)
    # =========================================================================
    {
        "sku": "REV-NUT-01",
        "name": "HydroElectrolyte Hydration Drink Mix (30 Servings)",
        "description": "Optimal ratio of Sodium, Potassium, and Magnesium formulated for rapid cellular rehydration without sugar crashes.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("799.00"),
        "cost_price": Decimal("320.00"),
        "stock_quantity": 160,
        "image_url": "/images/products/recovery/hydroelectrolyte-hydration-drink-mix-30-servings.svg",
        "tags": ["electrolytes", "hydration", "drink_mix", "recovery"],
        "metadata_json": {"servings": 30, "flavor": "Citrus Burst", "sugar_free": True},
    },
    {
        "sku": "REV-NUT-02",
        "name": "DeepTissue Muscle Massage Gun (4 Speeds)",
        "description": "High-torque brushless motor delivering 3200 RPM percussion therapy to relieve muscle knots and soreness.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("2999.00"),
        "cost_price": Decimal("1400.00"),
        "stock_quantity": 40,
        "image_url": "/images/products/recovery/deeptissue-muscle-massage-gun-4-speeds.svg",
        "tags": ["massage_gun", "recovery", "percussion", "muscle_care"],
        "metadata_json": {"heads_included": "4 Attachments", "battery_life": "6 Hours"},
    },
    {
        "sku": "REV-NUT-03",
        "name": "High-Density Grid Foam Muscle Roller (18-Inch)",
        "description": "Multi-density grid pattern designed for myofascial release, tight IT bands, calves, and lower back.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("699.00"),
        "cost_price": Decimal("260.00"),
        "stock_quantity": 130,
        "image_url": "/images/products/recovery/high-density-grid-foam-muscle-roller-18-inch.svg",
        "tags": ["foam_roller", "recovery", "myofascial", "stretching"],
        "metadata_json": {"length": "18 Inches", "material": "EVA Foam with rigid core"},
    },
    {
        "sku": "REV-NUT-04",
        "name": "Endurance Energy Gels Variety Box (12 Pack)",
        "description": "Fast-acting maltodextrin and fructose carbohydrate gels enriched with BCAAs for sustained running stamina.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("849.00"),
        "cost_price": Decimal("350.00"),
        "stock_quantity": 140,
        "image_url": "/images/products/recovery/endurance-energy-gels-variety-box-12-pack.svg",
        "tags": ["energy_gel", "nutrition", "marathon", "carbs"],
        "metadata_json": {"pack_count": 12, "calories_per_gel": 100, "caffeine": "Optional 25mg"},
    },
    {
        "sku": "REV-NUT-05",
        "name": "PlantPro 100% Vegan Protein Powder (1kg)",
        "description": "Pea and brown rice protein blend delivering 25g clean protein and 5g BCAAs per serving with zero dairy.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("1899.00"),
        "cost_price": Decimal("850.00"),
        "stock_quantity": 85,
        "image_url": "/images/products/recovery/plantpro-100-vegan-protein-powder-1kg.svg",
        "tags": ["protein", "vegan", "recovery", "plant_based"],
        "metadata_json": {"net_weight": "1kg", "protein_per_serving": "25g", "flavor": "Rich Cocoa"},
    },
    {
        "sku": "REV-NUT-06",
        "name": "AeroRecovery Cold Therapy Ice Compression Wrap",
        "description": "Customizable gel pack with compression strap for treating knee sprains, swelling, and ankle inflammation.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("599.00"),
        "cost_price": Decimal("210.00"),
        "stock_quantity": 95,
        "image_url": "/images/products/recovery/aerorecovery-cold-therapy-ice-compression-wrap.svg",
        "tags": ["ice_pack", "cold_therapy", "inflammation", "knee"],
        "metadata_json": {"reusable": True, "target_joints": "Knee, Elbow, Ankle"},
    },
    {
        "sku": "REV-NUT-07",
        "name": "Targeted Muscle Trigger Point Lacrosse Ball",
        "description": "Dense solid rubber ball for deep localized myofascial release on glutes, plantar fascia, and shoulders.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("249.00"),
        "cost_price": Decimal("70.00"),
        "stock_quantity": 250,
        "image_url": "/images/products/recovery/targeted-muscle-trigger-point-lacrosse-ball.svg",
        "tags": ["massage_ball", "trigger_point", "mobility", "feet"],
        "metadata_json": {"diameter": "6.3cm", "density": "High Density Rubber"},
    },
    {
        "sku": "REV-NUT-08",
        "name": "Spiky Plantar Fascia Foot Massage Roller",
        "description": "Contoured spiky foot roller stimulating blood flow and releasing tension in tired arches and heels.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("299.00"),
        "cost_price": Decimal("95.00"),
        "stock_quantity": 180,
        "image_url": "/images/products/recovery/spiky-plantar-fascia-foot-massage-roller.svg",
        "tags": ["foot_roller", "plantar_fasciitis", "recovery", "feet"],
        "metadata_json": {"material": "TPR Ergonomic Nodule Core"},
    },
    {
        "sku": "REV-NUT-09",
        "name": "Cooling Instant Relief Sports Towel",
        "description": "Hyper-evaporative cooling towel that drops up to 15 degrees below ambient temperature when wet.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("199.00"),
        "cost_price": Decimal("60.00"),
        "stock_quantity": 220,
        "image_url": "/images/products/recovery/cooling-instant-relief-sports-towel.svg",
        "tags": ["cooling_towel", "heat_relief", "summer", "workout"],
        "metadata_json": {"cooling_duration": "Up to 3 Hours", "chemical_free": True},
    },
    {
        "sku": "REV-NUT-10",
        "name": "Magnesium Glycinate Sleep & Muscle Tablets (60ct)",
        "description": "Highly absorbable chelated magnesium complex reducing nocturnal leg cramps and promoting deep REM sleep.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("649.00"),
        "cost_price": Decimal("240.00"),
        "stock_quantity": 110,
        "image_url": "/images/products/recovery/magnesium-glycinate-sleep-and-muscle-tablets-60ct.svg",
        "tags": ["magnesium", "sleep", "muscle_cramps", "supplements"],
        "metadata_json": {"servings": 60, "form": "Chelated Glycinate"},
    },
    {
        "sku": "REV-NUT-11",
        "name": "Heavy-Duty Mobility Recovery Resistance Bands (Set of 3)",
        "description": "Fabric non-slip loop bands for glute activation, hip mobility drills, and physical therapy rehab.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("499.00"),
        "cost_price": Decimal("180.00"),
        "stock_quantity": 150,
        "image_url": "/images/products/recovery/heavy-duty-mobility-recovery-resistance-bands-set-of-3.svg",
        "tags": ["resistance_bands", "mobility", "glutes", "warmup"],
        "metadata_json": {"levels": ["Light", "Medium", "Heavy"], "material": "Fabric Cotton-Latex"},
    },
    {
        "sku": "REV-NUT-12",
        "name": "Marathon Finisher Complete Recovery Nutrition Kit",
        "description": "All-in-one post-race box containing 2 recovery shakes, 4 electrolyte sachets, and cold compression therapy gel.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("1599.00"),
        "cost_price": Decimal("680.00"),
        "stock_quantity": 50,
        "image_url": "/images/products/recovery/marathon-finisher-complete-recovery-nutrition-kit.svg",
        "tags": ["recovery_kit", "bundle", "nutrition", "marathon_finisher"],
        "metadata_json": {"includes": "2x Protein, 4x Electrolytes, 1x Cold Gel Pack"},
    },
    {
        "sku": "REV-NUT-13",
        "name": "NitroFuel BCAA Intra-Workout Powder (400g)",
        "description": "Instantized 2:1:1 BCAAs with L-Glutamine and coconut water powder to prevent muscle breakdown during long efforts.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("1199.00"),
        "cost_price": Decimal("480.00"),
        "stock_quantity": 90,
        "image_url": "/images/products/recovery/nitrofuel-bcaa-intra-workout-powder-400g.svg",
        "tags": ["bcaa", "intra_workout", "hydration", "amino_acids"],
        "metadata_json": {"servings": 40, "ratio": "2:1:1 Leucine", "flavor": "Green Apple"},
    },
    {
        "sku": "REV-NUT-14",
        "name": "AeroRecovery Vibrating Foam Muscle Roller",
        "description": "High-intensity 3-speed vibrating foam roller combining deep tissue myofascial release with rhythmic vibration therapy.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("1899.00"),
        "cost_price": Decimal("850.00"),
        "stock_quantity": 45,
        "image_url": "/images/products/recovery/aerorecovery-vibrating-foam-muscle-roller.svg",
        "tags": ["vibrating_roller", "foam_roller", "recovery", "vibration"],
        "metadata_json": {"speeds": 3, "battery": "Rechargeable 3h"},
    },
    {
        "sku": "REV-NUT-15",
        "name": "HydroBurst High-Sodium Electrolyte Tablets (20ct)",
        "description": "Effervescent electrolyte drink tablets with 500mg sodium per tablet for hot summer runs and heavy sweaters.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("399.00"),
        "cost_price": Decimal("140.00"),
        "stock_quantity": 180,
        "image_url": "/images/products/recovery/hydroburst-high-sodium-electrolyte-tablets-20ct.svg",
        "tags": ["electrolyte_tablets", "hydration", "sodium", "cramps"],
        "metadata_json": {"tablets": 20, "sodium_per_tab": "500mg", "flavor": "Lemon Lime"},
    },
    {
        "sku": "REV-NUT-16",
        "name": "ProMobility Compression Floss Bands (Pair)",
        "description": "Latex compression bands for joint tack-and-floss mobility, improving ankle dorsiflexion and knee range of motion.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("449.00"),
        "cost_price": Decimal("160.00"),
        "stock_quantity": 125,
        "image_url": "/images/products/recovery/promobility-compression-floss-bands-pair.svg",
        "tags": ["floss_bands", "mobility", "joints", "rehab"],
        "metadata_json": {"thickness": "1.0mm & 1.5mm", "length": "200cm"},
    },
    {
        "sku": "REV-NUT-17",
        "name": "Arnica & Menthol Muscle Soothing Cream (100g)",
        "description": "Fast-absorbing topical cream with organic Arnica Montana and natural cooling menthol for sore joints and tendons.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("349.00"),
        "cost_price": Decimal("110.00"),
        "stock_quantity": 190,
        "image_url": "/images/products/recovery/arnica-and-menthol-muscle-soothing-cream-100g.svg",
        "tags": ["arnica", "menthol", "muscle_cream", "pain_relief"],
        "metadata_json": {"net_weight": "100g", "cooling": "Fast-acting"},
    },
    {
        "sku": "REV-NUT-18",
        "name": "Collagen Joint & Tendon Recovery Peptides (300g)",
        "description": "Hydrolyzed Type I & III collagen peptides enriched with Vitamin C for ligament elasticity and tendon recovery.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("1499.00"),
        "cost_price": Decimal("620.00"),
        "stock_quantity": 70,
        "image_url": "/images/products/recovery/collagen-joint-and-tendon-recovery-peptides-300g.svg",
        "tags": ["collagen", "joints", "tendon", "peptides"],
        "metadata_json": {"servings": 30, "collagen_per_serving": "10g"},
    },
    {
        "sku": "REV-NUT-19",
        "name": "Percussion Mini Compact Travel Massage Gun",
        "description": "Pocket-sized 450g travel percussion massage gun with USB-C fast charging and 4 silicone massage heads.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("2499.00"),
        "cost_price": Decimal("1100.00"),
        "stock_quantity": 55,
        "image_url": "/images/products/recovery/percussion-mini-compact-travel-massage-gun.svg",
        "tags": ["mini_massage_gun", "travel", "percussion", "portable"],
        "metadata_json": {"weight": "450g", "charging": "USB-C Fast Charge"},
    },
    {
        "sku": "REV-NUT-20",
        "name": "AeroCompression Pneumatic Recovery Leg Sleeves",
        "description": "Dynamic 4-chamber sequential pneumatic air compression boots for rapid lactate flush and post-marathon recovery.",
        "category": "Nutrition & Recovery",
        "category_slug": "nutrition-recovery",
        "price": Decimal("5999.00"),
        "cost_price": Decimal("2800.00"),
        "stock_quantity": 25,
        "image_url": "/images/products/recovery/aerocompression-pneumatic-recovery-leg-sleeves.svg",
        "tags": ["compression_boots", "pneumatic", "lactate_flush", "elite_recovery"],
        "metadata_json": {"chambers": 4, "pressure_range": "20-200 mmHg"},
    },
]
